version: "3.9"

services:
  client:
    build: ./client
    container_name: client
    networks:
      - day2
    ports:
      - "3000:3000"
  server:
    build: ./server
    container_name: server
    networks:
      - day2
    depends_on:
      - mongo

  mongo:
    build: ./DB
    container_name: mongo
    networks:
      - day2
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  day2:
    external: true